### ISSUE TITLE
Résolution d'un bug de kick au Skyblock

### ISSUE THREAD

**Issue by minendio** [Bakalexis/uni-craft#26]
**Décrire le bug**
je me suis fait kick sans raison pour fly alors que je ne faisais que marcher et courir

**Comment le reproduire**
1. Aller sur le serveur '...'
2. Expliquer comment reproduire le bug
3. Le problème en question

**Que devrait-il se passer ?**
Vous pouvez écrire ici ce qu'il devrait se passer au lieu du bug rencontré

**Screenshots**
![2019-11-21_16 11 25](https://user-images.githubusercontent.com/58041111/69350954-cb9f9c80-0c7a-11ea-81c4-7bd0f1797869.png)

**Serveur sur lequel le bug est rencontré**
 - Skyblock

**Comment by Bakalexis** [comment]
Correction d'un bug qui kickait certains joueurs de la 1.12+ pour cause de "Fly"
