### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ilyas-r** [Bakalexis/uni-craft#48]
**Décrire le bug**
Dans le chat certains messages ont du mal à être afficher.

**Comment le reproduire**
1. Rejoindre l' UHC Run 1v1 ou 3v3
2. Certains messages dans le chat (avec couleurs) auront du mal à s'afficher correctement.

**Que devrait-il se passer ?**
Par exemple :
En rejoignant l'UHC Run 1v1, ce message est affiché dans le chat : "IkaRio_ &7rejoint la partie &a(1/27)"
Alors que normalement le message suivant aurait dû être affiché comme tel : "IkaRio_ rejoint la partie (1/27)" (avec les bonnes couleurs).

**Screenshots**
[https://media.discordapp.net/attachments/647798368491274271/647799824959275019/unknown.png?width=882&height=468](url)

**Serveur sur lequel le bug est rencontré**
 - UHC

**Autre chose à ajouter ?**
Merci d'avoir lu ce poste ! 👍 

IkaRio

**Comment by Bakalexis** [comment]
Le bug a été résolu
